//created on: 17/04/2015
package org.cloudbus.mcweb.rules

//list any import classes here.
import org.cloudbus.mcweb.rules.Message;
import org.cloudbus.mcweb.rules.Relation;
import org.cloudbus.mcweb.rules.ITransitiveRelation;
import org.cloudbus.mcweb.rules.IReflexiveRelation;

import java.util.*;


//declare any global variables here

// ========================= Custom types =========================
declare Location
   code : String
end

// Left hand side (LHS) domain contains Right hand side (RHS) domain 
/*declare Contains
   lhs : String
   rhs : String
end*/

rule "Reflective Contains"
when
	Location($code : code)
then 
	insert(new Relation($code, $code, RelationType.REFLEXIVE));
end

rule "Transitive Contains"
when
	ITransitiveRelation($code1 : lhs, $code2 : rhs != $code1, $clazz : class)
	ITransitiveRelation(lhs == $code2, $code3 : rhs != $code2, class == $clazz)
	not(ITransitiveRelation(lhs == $code1, lhs == $code3, class == $clazz)) // Do not insert existing relations
then 
	//System.out.printf("%s = %s = %s\n", $code1, $code2, $code3);
	insert(new Relations.Contains($code1, $code3));
end
// ========================= ======================== =========================

// ========================= Inject Facts =========================
rule "European Union members"
salience 100
when
then
	Location eu = new Location("EU");
	insert(eu);
	
	String[] codes = new String[] { "AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR", "GB", "GR", "HU", "HR", "IE", "IT", "LT", "LU", "LV", "MT", "NL", "PO", "PT", "RO", "SE", "SI", "SK" };
	for(String c : codes) {
		Location l = new Location(c);
		insert(l);
		insert (new Relations.Contains("EU", c));
	}
end

rule "EuroZone members"
salience 100
when
then
	Location euz = new Location("EUZ");
	insert(euz);
	// EU contains all Eurozone countries.
	insert(new Relations.Contains("EU", "EUZ"));
	
	String[] codes = new String[] {"AT", "BE", "CY", "EE", "FI", "FR", "DE", "GR", "IE", "IT", "LV", "LT", "LU", "MT", "PT", "SK", "SI", "ES" };
	for(String c : codes) {
		Location l = new Location(c);
		insert(l);
		insert (new Relations.Contains("EUZ", c));
	}
end

// ========================= ======================== =========================

// ========================= DEBUG =========================
rule "Print all contains"
when
	Relations.Contains($code1 : lhs, $code2 : rhs)
then
	System.out.println($code1 + " <- " + $code2);
end

// ========================= ======================== =========================




rule "Hello World"
when
  message:Message (type == "Hello")
then
  message.printMessage();
end
